version: "3.9"

# This will apply in local development.
# In ci this file will be replaced by `docker-compose.ci.yml`

services:
  
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui

    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=eci
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=good-bee-12610-eu1-kafka.upstash.io:9092
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-256
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username="Z29vZC1iZWUtMTI2MTAkvshk1eLPUKtU8Qwe9V7GL7XuddUO9xP-ZTNl1UZFiFA" password="Vqfy9Vi7QbpVXDHFDky8OWNFQ0YjpptG4DN-hZwPoi4XVhGqMX7bhWAZBV-L5ZlUVHWeWQ==";
      - KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL=SASL
